skip-mev/skip-go-app

src/components/SkipBanner.tsx
=> remove button from banner

src/components/TransactionDialog/TransactionDialogContent.tsx
=> Clarify relayer warning

src/solve/form.ts
This simply moves the query for the initial user balance of the destination token to take place before the transaction is submitted. This is required when we're submitting txs on Osmosis that don't get relayed anywhere because they'll get finalized before the initial balance query -- tricking our querying into thinking the tx never finalizes
=> [ENG-1452] Fix transaction completion tracking for single chain txs

src/components/TransactionDialog/TransactionDialogContent.tsx
https://www.loom.com/share/db4100cdaf9e4e86b0c6568cb0d002e9?sid=4845d453-feb5-49bb-af0f-7155b85a3629
=> [ENG-1513] Scroll relay warning into view when opened

package-lock.json, package.json, src/components/TransactionDialog/TransactionDialogContent.tsx, src/config/index.ts, src/solve/form.ts, src/solve/utils.ts, src/utils/utils.ts
Handle chains that don't support memos. This was primarily a backend change, but updated the frontend to handle the new logic.
Akash is an example of this.
=> [ENG-1479] Handle supports memo

package-lock.json, package.json, src/solve/form.ts, src/utils/utils.ts
**Does not include EVMOS or Injective, will address separately**
=> [ENG-1492] Support Ledger (again)

src/components/TransactionDialog/TransactionDialogContent.tsx
Fixes regression where errors in route execution fail silently
=> [ENG-1558] Handle no gas error

src/components/TransactionDialog/TransactionDialogContent.tsx, src/solve/execute-route.ts, src/utils/utils.ts
=> [ENG-1431] Add explorer links to transactions

src/components/SwapWidget/SwapWidget.tsx, src/components/SwapWidget/useSwapWidget.ts, src/constants/chains.ts, src/pages/_app.tsx
also fixes problem where no message was shown when no route was found
=> support celestia

src/components/WalletModal/WalletModal.tsx
=> change display name of Metamask Snap

src/components/AssetValue.tsx, src/components/ChainSymbol.tsx, src/components/HistoryDialog/HistoryList.tsx, src/components/JsonDialog/index.tsx
- [Swap tx status emojis with icons [SPE-312]](https://github.com/skip-mev/ibc-dot-fun/commit/ff28368725ff4fbf0c38837ec9efc560607c80ab)
- [Update tx history chain symbol resolver [SPE-316]](https://github.com/skip-mev/ibc-dot-fun/commit/6aae8eb381b7ffc818ae2c11580fe2cac34f288a)
=> fix: resolve tx dialog feedbacks and bugs

src/components/AssetInput.tsx, src/components/SwapWidget/useSwapWidget.ts
This PR improves AssetInput component usability by preventing negative and other invalid values, basically anything except than numbers and periods/commas.
https://github.com/skip-mev/ibc-dot-fun/assets/8220954/bcfb945d-a304-4201-8ae0-d3fbd288f1f0
=> [SPE-311] prevent AssetInput negative and invalid values

package-lock.json, package.json, src/components/AssetInput.tsx, src/components/AssetSelect/AssetSelectContent.tsx, src/components/SwapWidget/SwapWidget.tsx, src/components/SwapWidget/useSwapWidget.ts, src/components/TransactionDialog/TransactionDialogContent.tsx, src/components/TransactionSuccessView.tsx, src/context/assets.tsx, src/cosmos/index.ts, src/pages/_app.tsx, src/pages/index.tsx, src/solve/context.tsx, src/utils/utils.ts
=> Evm dogfooding

.gitignore, next.config.js, package-lock.json, package.json, sentry.client.config.ts, sentry.edge.config.ts, sentry.server.config.ts
This PR adds Sentry integration which follows the pattern as configured in https://github.com/skip-mev/dydx-dashboard/blob/staging/next.config.js.
=> [SPE-254] feat: add sentry integration

src/solve/queries.ts
This PR change the assets query to incl. cw20 assets
=> [SPE-383] Support CW20 Swaps

package-lock.json, src/components/AssetInput.tsx, src/components/SwapWidget/SwapWidget.tsx, src/components/UsdValue.tsx, src/hooks/useUsdValue.ts, src/utils/llama.ts
This PR adds the USD value for both in and out asset using `https://coins.llama.fi/prices/current/coingecko:${id}` endpoint.
https://github.com/skip-mev/ibc-dot-fun/assets/8220954/4390f2fe-97b9-4831-8c4f-ef52baf6d9ca
=> [FRE-385] Show USD values for in and out asset

.github/workflows/branches.yml
This PR attempts to sync dev branch with latest ~staging~ main branch.
=> [FRE-337] gh action to sync main → dev

src/components/UsdValue.tsx
This PR fixes the usd differ render loop which may crash user's browser if kept running for a while.
=> [FRE-392] rework usd diff internal context

src/components/AssetInput.tsx, src/components/SimpleTooltip.tsx
This PR resolves a longstanding issue where inputting max balance somehow returns negative and other comma related issues.
https://github.com/skip-mev/ibc-dot-fun/assets/8220954/e9294da8-9db5-4112-ade8-4cadded7bdf2
=> [FRE-377] fix amount input and balance rendering

package-lock.json, src/components/UsdValue.tsx, src/hooks/useUsdValue.ts
This PR adds a fallback message when usd value cannot be retrieved.
=> [FRE-401] Handle assets that does not have coingecko ID

package-lock.json, package.json, src/components/HistoryDialog/HistoryList.tsx, src/components/HistoryDialog/index.tsx
=> [FRE-420] Handle tx history list overflow

src/components/RouteDisplay.tsx
=> Handle swap exact out in route display

src/components/TransactionDialog/TransactionDialogContent.tsx, src/utils/error.ts
tested on my personal sentry account
=> [FRE-381] send anonymized transaction errors to sentry

src/components/SwapWidget/SwapWidget.tsx, src/components/SwapWidget/useSwapWidget.ts, src/components/VersionCheck.tsx, src/components/WalletModal/WalletModal.tsx, src/components/WalletModal/context.tsx, src/context/track-wallet.ts, src/hooks/useAccount.ts, src/test/index.tsx
=> [FRE-526] refactor: rework account tracking on chain change

src/components/TransactionDialog/TransactionDialogContent.tsx
=> fre 516 and fre 517

src/components/SwapWidget/SwapWidget.tsx, src/components/SwapWidget/useSwapWidget.ts, src/components/WalletModal/WalletModal.tsx, src/context/track-wallet.ts, src/hooks/useAccount.ts, src/solve/context.tsx
=> [FRE-509] refactor: rework wallet connection tracking

src/components/TransactionDialog/AlertCollapse.tsx, src/components/TransactionDialog/TransactionDialogContent.tsx, src/hooks/useAccount.ts
=> [FRE-621] ledger warning cctp from noble

src/utils/api.ts
=> fix: borked proxy

src/layouts/default.tsx, src/pages/_app.tsx, src/pages/index.tsx
=> [FRE-643] Extract default layout

src/components/Help.tsx, src/context/assets.tsx, src/layouts/default.tsx
=> Add help to discord link

src/components/RouteDisplay/SwapStep.tsx, src/constants/swap-venues.ts
- Add testnet initia dex prettyName
- Make prettyName access optional
=> Add testnet initia dex prettyName

package-lock.json, package.json, src/pages/index.tsx
Update widget version to 2.1.0
=> Bump widget version to 2.1.0

package-lock.json, package.json
=> Bump widget version to v2.1.1

package-lock.json, package.json
=> Bump widget version to 2.1.1

package-lock.json, package.json
=> Bump widget to v2.4.8

package-lock.json, package.json
Sync prod with staging (bump widget to v2.4.8)
=> Sync prod with staging

src/pages/index.tsx
=> add mobile placeholder

src/pages/api/sentry.ts
whoops, didn't realize i needed to transform the data type and specify content-type `application/octet-stream`
=> Fix body request data format of sentry api request

src/pages/index.tsx, vercel.d.ts
this introduce 4 env var that can configured in vercel
```
readonly NEXT_PUBLIC_SHOW_BANNER?: string;
readonly NEXT_PUBLIC_BANNER_MESSAGE?: string;
readonly NEXT_PUBLIC_BANNER_LINK?: string;
readonly NEXT_PUBLIC_BANNER_TITLE?: string;
```
=> add banner

.github/workflows/deploy-dev.yml, .github/workflows/deploy-testnet-dev.yml, .github/workflows/deploy-testnet.yml
- **try setting job permissions**
- **bump checkout action version**
=> plas 106 fix deployments
