- README.md
- example.env
- src/solve/api.ts
This changes converts the API_URL to an environment variable.
This allows Next JS to set the API URL through environment variables in Vercel -- allowing us to have two different deployments simulataneously:
* A production deployment that depends on the production API
* A dev deployment that depends on the dev API
The new deployment flow will be: 
1. **Open PRs targeting the `staging` branch**: PRs opened _from_ any branch other than `staging` will preview using the dev APIs. (https://solve-dev.skip.money)
2. **Staging will deploy to staging.ibc.fun using production APIs**: After the PR is merged, the staging branch update the deployment at staging.skip.money -- which will always use the production APIs. 
3. Open a PR from staging into main to update ibc.fun
> [ENG-1462]Convert API URL to environment variable

- src/config/index.ts
This PR changes the swap venue name to use the new contract, not to be merged until server has pushed all the changes to prod
> Update swap venue naming for new contract

- src/analytics.ts
- src/components/TransactionDialog/TransactionDialogContent.tsx
- src/solve/client/client.ts
- src/solve/client/transaction.ts
- src/solve/form.ts
- src/solve/types.ts
Very basic usage of the lifecycle APIs. I plan to overhaul this part entirely but will likely take a day or two.
> lifecycle tracking v0

- src/solve/form.ts
`GasPrice.fromString` fails when the denom is an ibc denom.
I'm 98% sure we don't even need this code, but I don't want to inadvertently break something. Will handle in the refactor I'm working on.
> Handle ibc denoms as fees

- src/solve/form.ts
- src/utils/utils.ts
Increases the gas needed to 300,000 for transfer and 1,500,000 for swaps as the amount needed on Osmosis has increased.
- Gas needed increased
- src/solve/form.ts
Upping the gas needed to 300,000 for transfers and 1,500,000, increase of 50% since setting it automatically has issues for Neutron swapping.
**Previously**
We use gasNeeded for checking if user has enough of the fee token on all changes they need to submit a tx, not sure how to get an estimate here. This is probably why we are hardcoding it now.
For this PR, I am setting auto for actually submitting the tx to avoid failure, but leaving in the hardcoded value for checking if the gas token exists. The effect of this is 
1) If the auto gas is less than the hard coded value, then we might error even if the user has enough of the …
> [ENG-1678] Increase gas needed

- src/components/SwapWidget/SwapWidget.tsx
- src/components/SwapWidget/useSwapWidget.ts
- src/components/__tests__/SwapWidget.test.tsx
If user selects a destination token, then changes the destination chain, attempt to find equivalent token on new source chain.
Also moves the form state update logic to the `useFormValues` hook
> [ENG-1696] Find equivalent destination token when destination chain changes

- src/components/SwapWidget/useSwapWidget.ts
The chain name returned by our API and the chain name cosmos kit expects don't always match. Using the record from the chain registry will always be the correct one.
> use correct chain name in useSwapWidget

- src/components/RouteDisplay.tsx
- src/context/assets.tsx
Previously when an asset could not be found in the `RouteDisplay` components, it would not show that step. Now this is handled a little more intelligently.
> Handle missing assets in route display

- package-lock.json
- package.json
- Update the chain-registry submodule, which [includes Celestia now](https://github.com/cosmos/chain-registry/tree/master/celestia)
- Update Skip Router to version that also includes Celestia
> Support Celestia

- package-lock.json
- package.json
- src/components/ChainSelect/ChainSelectContent.tsx
- src/components/ChainSymbol.tsx
- src/components/HistoryDialog/index.tsx
- src/components/RouteDisplay.tsx
- src/components/TransactionDialog/TransactionDialogContent.tsx
- src/context/tx-history.ts
- src/cosmos/index.ts
- src/pages/index.tsx
- Bumps `@skip-router/core` to version that uses the V2 lifecycle tracking (PR for skip-router updates coming today or tomorrow)
- Use `onTransactionBroadcast` option on Skip Router to store transaction history upon broadcast (rather than route completion)
- On page load, update pending transactions in history
- Small style updates on tx history
> Use V2 lifecycle tracking

- .env.example
- .gitignore
- env.d.ts
- example.env
- package-lock.json
- src/components/__tests__/SwapWidget.test.tsx
- src/constants/api.ts
- src/solve/context.tsx
This PR allows overriding API url via env and fallbacks to prod endpoint provided from `@skip-router/core`.
> [SPE-336] Allow override api endpoint from env vars

- src/config/index.ts
This PR adds terra astroport to the list of swap venues and changes the naming to incl the network for astroport dexes
> Add Terra Astroport Swap Venue Support

- src/components/AssetInput.tsx
This PR adds (max) slippage information on the main swap interface, specifically below the swap out amount.
https://github.com/skip-mev/ibc-dot-fun/assets/8220954/8b6878b2-6ed8-4e44-9854-30a4249dee2f
> [SPE-340] Add slippage info below swap out amount

- src/components/BuildInfo.tsx
- src/pages/_app.tsx
This PR adds a conditional build info popup containing relevant data for debugging, such as node env, is vercel, api url, commit ref, and pr link.
https://linear.app/skip/issue/SPE-338/add-debug-information-in-the-corner-when-not-running-in-a-production
> [SPE-338] Add debug information in the corner when not running in a production environment

- src/components/TransactionDialog/TransactionDialogContent.tsx
- src/constants/constants.ts
- src/constants/finality.ts
This PR updates the finality time display in tx dialog with mappings from the [Axelar documentation](https://docs.axelar.dev/learn/txduration#common-finality-time-for-interchain-transactions).
| Avalanche | Ethereum | Polygon |
|-|-|-|
|![CleanShot 2023-11-07 at 03 00 32@2x](https://github.com/skip-mev/ibc-dot-fun/assets/8220954/970e4622-02c7-4c75-a19e-3bc0ea40761a)|![CleanShot 2023-11-07 at 02 59 46@2x](https://github.com/skip-mev/ibc-dot-fun/assets/8220954/3ef547ef-7124-42d7-a291-e5c54413b5ed)|![CleanShot 2023-11-07 at 02 59 31@2x](https://github.com/skip-mev/ibc-dot-fun/assets/8220954/dfe7beba-91d3-4026-a0c7-3026c2be315b)|
> [SPE-308] show finality times for various evm chains

- src/components/SwapWidget/SwapWidget.tsx
- src/components/SwapWidget/useSwapWidget.ts
Properly anticipate possible errors returned by the route endpoint, such as when the swap amount too small and unsupported native evm tokens
> Add more descriptive errors for routes

- src/components/TransactionDialog/TransactionDialogContent.tsx
Previously we were only displaying the finality time estimate when the source chain was EVM, now we check both source and destination.
> [SPE-370] Show finality estimate when destination chain is EVM

- src/components/AssetInput.tsx
- src/components/PriceImpactWarning.tsx
- src/components/SwapWidget/SwapDetails.tsx
- src/components/SwapWidget/SwapWidget.tsx
- src/components/SwapWidget/useSwapWidget.ts
- src/components/TransactionDialog/index.tsx
- src/context/disclosures.ts
- src/utils/utils.ts
Updates ibc.fun to:
- Use USD values from the API
- Display price impact in the `SwapDetails` component
- If price impact is higher than a configurable threshold (I set to 1%, let me know what you'd actually like it to be):
- Open the SwapDetails accordion to highlight the high price impact
- Display a warning popup before submitting any transactions 
https://github.com/skip-mev/ibc-dot-fun/assets/91888455/7848c0a0-4b9c-44eb-a506-ec81ce2d7e0f
> Display warning on high price impact

- src/components/AssetInput.tsx
- src/utils/number.ts
by formatting back and forth, we can show the comma separator and still get the clean value
> [FRE-498] Format numbers using comma separator every three digits

- src/components/WalletModal/WalletListItem.tsx
- src/utils/os.ts
Currently mobile wallets not working because if the wallet mode is `wallet-connect` it needs to `initClient()` and get generate the qr code from `qrUrl` 
https://linear.app/skip/issue/FRE-560/generate-qr-code-for-mobile-wallets
> fix: hide mode wallet-connect on mobile

- src/components/HistoryDialog/HistoryList.tsx
related to https://linear.app/skip/issue/FRE-597/stuck-watching-transaction-load-on-transfer-failure 
users that have that tx in their history will have infinite fetch.
> feat: remove tx history failed fetch 4 times

- src/context/assets.tsx
This PR fixes a UI and logic delay by removing router's logic to get FeeAsset info. Reason is router does the checking by iterating its internal deprecated chain registry data.
> fix: drop router fee info checker

- package-lock.json
- package.json
- src/hooks/useURLQueryParams.tsx
- src/lib/edge-config.ts
- src/middleware.ts
- src/pages/api/fee-assets/[chainID].ts
- src/pages/blocked.tsx
- src/utils/chain.client.ts
> [FRE-906] Feat/geo block
